services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env.development.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-wallet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-analytic}
      POSTGRES_DB: ${POSTGRES_DB:-wallet_analytic}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    networks:
      - otel-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-wallet} -d ${POSTGRES_DB:-wallet_analytic}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
