name: Build API App

on:
  push:
    paths:
      - 'apps/api/**'
      - 'packages/shared/**'
      - 'packages/db/**'
      - '.github/workflows/build-api.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build API app
        run: bun run --filter=@wallet-analytic/api build
