name: Build Web App

on:
  push:
    paths:
      - 'apps/web/**'
      - '.github/workflows/web.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build web app
        run: bun run --filter=@wallet-analytic/web build
