name: Mirror to GitVerse

on:
  push:
    branches: [master]

jobs:
  mirror:
    if: contains(github.server_url, 'github.com')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config --global user.name "sf"
          git config --global user.email "scoffs@internet.ru"

      - name: Install git-filter-repo
        run: |
          curl -sL https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo -o /usr/local/bin/git-filter-repo
          chmod +x /usr/local/bin/git-filter-repo

      - name: Rewrite ALL commit authors with git-filter-repo
        run: |
          git filter-repo --force --commit-callback '
            commit.author_name = b"sf"
            commit.author_email = b"scoffs@internet.ru"
            commit.committer_name = b"sf"
            commit.committer_email = b"scoffs@internet.ru"
          '

      - name: Push to GitVerse mirror
        run: |
          git remote remove gitverse 2>/dev/null || true
          git remote add gitverse https://${{ secrets.GITVERSE_USER }}:${{ secrets.GITVERSE_TOKEN }}@gitverse.ru/wl/core.git
          git push gitverse --mirror --force
